/* ---------------------------------------------------------------------------
   lib/text.js

   String judgements shared by the repair rules and the audits. Nothing in
   here touches the DOM, which is deliberate: these are the decisions that
   were previously written inline, slightly differently, in each rule, and
   they are the decisions most likely to be wrong in an interesting way.

   Exposed as window.A11yText so it works when pasted into a code injection
   box, and loadable in Node for unit tests without a browser.
   --------------------------------------------------------------------------- */

(function (global) {
  'use strict';

  var IMAGE_EXTENSIONS = /\.(jpe?g|png|gif|webp|svg|avif|bmp|tiff?)$/i;

  /* Collapse runs of whitespace, including the non-breaking space that
     platform editors insert when an author presses space twice. An element
     whose only content is a non-breaking space is not named. */
  function normalize(value) {
    if (value === null || value === undefined) return '';
    return String(value).replace(/[\s ]+/g, ' ').trim();
  }

  /* True when an alt value is a filename carrying no information.

     The test is deliberately narrow. "Our 2024 team at the summer picnic"
     is prose and must survive; "DSC_0043.JPG" and "hero-image-final-2.png"
     are filenames and do not. The distinguishing feature is not the
     extension on its own, because "Figure 1. The site map." also ends in a
     dot, but an extension preceded by a token with no spaces. */
  function isFilenameAlt(alt) {
    var value = normalize(alt);
    if (!value) return false;
    if (!IMAGE_EXTENSIONS.test(value)) return false;
    if (/\s/.test(value)) return false;
    return /^[\w.-]+$/.test(value);
  }

  /* Link text that is identical on every item in a list, which is the
     summary block and blog grid failure. Matched against the normalized
     visible text, case insensitively. */
  var GENERIC_LINK_TEXT = [
    'read more', 'readmore', 'more', 'learn more', 'continue reading',
    'continue', 'details', 'view', 'view more', 'see more', 'click here',
    'here', 'this', 'link', 'go', 'open'
  ];

  function isGenericLinkText(text) {
    var value = normalize(text).toLowerCase().replace(/[.!…>\s]+$/, '');
    return GENERIC_LINK_TEXT.indexOf(value) !== -1;
  }

  /* Map a probe string, assembled from an element's test ids and class
     names, to a name we are confident enough to apply.

     Ordered most specific first. "close" is tested before "search" because
     a control named something like "search-close" is a close button. There
     is no fallback on purpose: a control we cannot identify is reported for
     a human to name in the editor, never guessed at. */
  var HINTS = [
    [/\bclose\b|\bdismiss\b|\bcancel\b/i, 'Close'],
    [/\bmenu\b|\bhamburger\b|\bburger\b|\bnav-toggle\b/i, 'Open menu'],
    [/\bsearch\b|\bmagnif/i, 'Search'],
    [/\bprev(ious)?\b|\bback\b|left-arrow|arrow-left/i, 'Previous'],
    [/\bnext\b|\bforward\b|right-arrow|arrow-right/i, 'Next'],
    [/\bplay\b/i, 'Play'],
    [/\bpause\b/i, 'Pause'],
    [/\bmute\b/i, 'Mute'],
    [/\bcart\b|\bbasket\b|\bbag\b/i, 'Cart'],
    [/\baccount\b|\bprofile\b|\blogin\b/i, 'Account']
  ];

  function hintFor(probe) {
    var value = normalize(probe);
    if (!value) return null;
    for (var i = 0; i < HINTS.length; i++) {
      if (HINTS[i][0].test(value)) return HINTS[i][1];
    }
    return null;
  }

  /* A CSS identifier generated by a closed platform, such as Wix's _1a2b3c
     or a hashed module class. Selectors built on these break on the next
     publish, so the rules refuse to use them and the verifier refuses to
     ship them. */
  function isGeneratedClassName(name) {
    var value = normalize(name);
    if (!value) return false;
    if (/^_[A-Za-z0-9]{4,}$/.test(value)) return true;
    if (/^[A-Za-z][\w-]*__[A-Za-z0-9]{5,}$/.test(value)) return true;
    return /^[A-Za-z][\w-]*-[a-f0-9]{6,}$/.test(value);
  }

  global.A11yText = {
    normalize: normalize,
    isFilenameAlt: isFilenameAlt,
    isGenericLinkText: isGenericLinkText,
    hintFor: hintFor,
    isGeneratedClassName: isGeneratedClassName,
    GENERIC_LINK_TEXT: GENERIC_LINK_TEXT
  };
})(typeof window !== 'undefined' ? window : this);
