/**
 * tools/catalogue-doc.mjs
 *
 * Generates docs/every-finding.md from tools/catalogue.mjs.
 *
 *   node tools/catalogue-doc.mjs            write the file
 *   node tools/catalogue-doc.mjs --check    fail if it is out of date
 *
 * A table of findings maintained by hand is a table of findings that is
 * wrong, so this one is not maintained by hand. CI runs the check form.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { CATALOGUE } from './catalogue.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'docs', 'every-finding.md');

function build() {
  const scannerMisses = CATALOGUE.filter((c) => !c.scanner);
  const behavioural = CATALOGUE.filter((c) => c.kind === 'behavioural');
  const absence = CATALOGUE.filter((c) => c.absence);

  const lines = [];
  lines.push('# Every finding');
  lines.push('');
  lines.push('Generated by `tools/catalogue-doc.mjs` from `tools/catalogue.mjs`.');
  lines.push('Do not edit this file. CI fails if it drifts from the catalogue.');
  lines.push('');
  lines.push('`' + CATALOGUE.length + '` findings. `' + behavioural.length + '` of them need a key press to');
  lines.push('detect, and `' + scannerMisses.length + '` are not reported by an off the shelf automated');
  lines.push('scanner at all. That second number is the argument for this repository');
  lines.push('existing: on a closed platform, the findings that decide whether a');
  lines.push('keyboard user can use the site are mostly the ones a scanner is silent');
  lines.push('about.');
  lines.push('');
  lines.push('## The table');
  lines.push('');
  lines.push('| Finding | WCAG | How it is found | Scanner reports it |');
  lines.push('|---|---|---|---|');
  for (const c of CATALOGUE) {
    lines.push('| `' + c.id + '` | ' + c.wcag + ' | ' + c.kind + ' | ' + (c.scanner ? 'yes' : 'no') + ' |');
  }
  lines.push('');
  lines.push('## What each one means');
  lines.push('');
  for (const c of CATALOGUE) {
    lines.push('### `' + c.id + '`');
    lines.push('');
    lines.push('WCAG ' + c.wcag + '. ' + (c.kind === 'behavioural'
      ? 'Found by driving the page and watching what moves.'
      : 'Found by reading the page.'));
    lines.push('');
    lines.push(c.summary);
    lines.push('');
  }
  lines.push('## Absence findings');
  lines.push('');
  lines.push('These ' + absence.length + ' report that something is not on the page at all, rather');
  lines.push('than that something on the page is wrong:');
  lines.push('');
  for (const c of absence) lines.push('- `' + c.id + '`');
  lines.push('');
  lines.push('They fire on an empty document, correctly, and that makes them useless as');
  lines.push('evidence that a failing example demonstrates its own defect. A blank HTML');
  lines.push('file would satisfy a test that only asked for "at least one finding".');
  lines.push('`test/pairs.test.mjs` therefore requires every failing example to produce at');
  lines.push('least one finding from outside this set, and runs every check against an');
  lines.push('empty document to confirm that nothing outside it fires there.');
  lines.push('');
  return lines.join('\n');
}

const built = build();

if (process.argv.includes('--check')) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== built) {
    console.error('docs/every-finding.md is out of date. Run: npm run docs');
    process.exit(1);
  }
  console.log('docs/every-finding.md is up to date (' + CATALOGUE.length + ' findings).');
} else {
  writeFileSync(OUT, built);
  console.log('Wrote docs/every-finding.md with ' + CATALOGUE.length + ' findings.');
}
