/**
 * tools/examples-doc.mjs
 *
 * Generates examples/README.md from tools/pairs.mjs.
 *
 *   node tools/examples-doc.mjs            write the file
 *   node tools/examples-doc.mjs --check    fail if it is out of date
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PAIRS } from './pairs.mjs';
import { byId } from './catalogue.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'examples', 'README.md');

function build() {
  const lines = [];
  lines.push('# Failing and corrected examples');
  lines.push('');
  lines.push('Generated by `tools/examples-doc.mjs` from `tools/pairs.mjs`.');
  lines.push('Do not edit this file. CI fails if it drifts.');
  lines.push('');
  lines.push('Each directory holds the same page twice: `fail.html` as the platform');
  lines.push('emits it, and `pass.html` as it should be. `test/pairs.test.mjs` asks three');
  lines.push('questions of every pair, and the third is the one that matters to anybody');
  lines.push('pasting the bundle into a client site:');
  lines.push('');
  lines.push('1. Does the failing page produce exactly the findings it claims?');
  lines.push('2. Is the corrected page clean of them?');
  lines.push('3. Does the shipped repair layer, injected into the failing page, earn the');
  lines.push('   same grade as correcting the page at source would?');
  lines.push('');
  lines.push('| Example | Rule | Findings proved | Left after repair |');
  lines.push('|---|---|---|---|');
  for (const pair of PAIRS) {
    const dir = pair.dir.replace('examples/', '');
    const found = pair.expect.map((id) => '`' + id + '`').join('<br>');
    const left = pair.residual.length
      ? pair.residual.map((id) => '`' + id + '`').join('<br>')
      : 'nothing';
    lines.push('| [`' + dir + '`](' + dir + '/) | `' + pair.rule + '` | ' + found + ' | ' + left + ' |');
  }
  lines.push('');
  lines.push('## What each pair proves');
  lines.push('');
  for (const pair of PAIRS) {
    lines.push('### ' + pair.dir.replace('examples/', ''));
    lines.push('');
    lines.push(pair.title + '.');
    lines.push('');
    for (const id of pair.expect) {
      const entry = byId(id);
      lines.push('- `' + id + '`, WCAG ' + entry.wcag + '. ' + entry.summary);
    }
    lines.push('');
    if (pair.residual.length) {
      lines.push('**The repair does not clear this one, and that is the point.** ' + pair.residualReason);
      lines.push('');
    }
  }
  return lines.join('\n');
}

const built = build();

if (process.argv.includes('--check')) {
  if (!existsSync(OUT) || readFileSync(OUT, 'utf8') !== built) {
    console.error('examples/README.md is out of date. Run: npm run docs');
    process.exit(1);
  }
  console.log('examples/README.md is up to date (' + PAIRS.length + ' pairs).');
} else {
  writeFileSync(OUT, built);
  console.log('Wrote examples/README.md with ' + PAIRS.length + ' pairs.');
}
